# Generated by Django 3.1.4 on 2021-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210606_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
